spring.application.name=microservice-api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=microservice-drivers
spring.cloud.gateway.routes[0].uri=${DRIVER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/drivers/**

spring.cloud.gateway.routes[1].id=microservice-orders
spring.cloud.gateway.routes[1].uri=${ORDER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.routes[2].id=microservice-assignments
spring.cloud.gateway.routes[2].uri=${ASSIGNMENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/assignments/**

spring.cloud.gateway.routes[3].id=microservice-drivers-swagger
spring.cloud.gateway.routes[3].uri=${DRIVER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[3].predicates[0]=Path=/v3/api-docs/drivers
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/v3/api-docs/drivers, /api/v1/v3/api-docs

spring.cloud.gateway.routes[4].id=microservice-orders-swagger
spring.cloud.gateway.routes[4].uri=${ORDER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[4].predicates[0]=Path=/v3/api-docs/orders
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/v3/api-docs/orders, /api/v1/v3/api-docs

spring.cloud.gateway.routes[5].id=microservice-assignments-swagger
spring.cloud.gateway.routes[5].uri=${ASSIGNMENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[5].predicates[0]=Path=/v3/api-docs/assignments
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/v3/api-docs/assignments, /api/v1/v3/api-docs

# Configuración del menú desplegable de Swagger UI
springdoc.swagger-ui.urls[0].name=Conductores (Drivers API)
springdoc.swagger-ui.urls[0].url=/v3/api-docs/drivers
springdoc.swagger-ui.urls[1].name=Ordenes (Orders API)
springdoc.swagger-ui.urls[1].url=/v3/api-docs/orders
springdoc.swagger-ui.urls[2].name=Asignaciones (Assignments API)
springdoc.swagger-ui.urls[2].url=/v3/api-docs/assignments

# Apaga el auto-descubrimiento del Gateway para que solo use tu lista manual
springdoc.swagger-ui.disable-swagger-default-url=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

jwt.secret=${JWT_SECRET:mySecretKeyEvaluacionApi2026SecureEnoughForHS256}

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

logging.level.org.springframework.cloud.gateway=INFO
